### ISSUE TITLE
data.get('string') or data['string']

### ISSUE THREAD

**Issue by jbzdarkid** [jayme-github/steamweb#4]
Which one do you want to use? It seems odd to have both of them.

**Comment by jayme-github** [comment]
True. But: :smile:
I tend to use `data['string']` when I want the code to raise an exception if the key is not present because it needs to be there (like [here](https://github.com/jayme-github/steamweb/blob/1e6d1f4823de7b32bde243cfdb686670908755ba/steamweb.py#L104-L110)) and I've no error handling for a case where it it not.
I use `data.get('string')` when a missing key is okay or I want to avoid conditions like `if 'string' in data and data['string']`

**Comment by jbzdarkid** [comment]
Okay. I guess I'll change things like 
    if data.get('message')
to
    if 'message' in data
