### ISSUE TITLE
if data.get('captcha_needed', False):

### ISSUE THREAD

**Issue by jbzdarkid** [jayme-github/steamweb#8]
This isn't functional. If the return from data.get() is 'False' (the string), the contents of the if statement will be executed.

When using data.get() (much like data[]) you need to compare the contents. This is why I was writing data.get('catpcha_needed') == True, I feel it reads better than data.get('captcha_needed', 'False') == True

**Comment by jbzdarkid** [comment]
A simple test for this is to try:

```
a = 'False'
if a:
    print a
```

and you will get a lovely output of False.

**Comment by jayme-github** [comment]
This is absolutely true but there was a time when steam returned strings that were not mapped to boolean types as values for `captcha_needed` for example. On the other hand they always returned false (mapped to False) or an empty string for False.

My intention with this was/is to take everything that is not clearly False as True and that worked very well for over a year now. That's why I had no intention to change that.
If you insist on this change I'll pull it over as it does not break anything now :smile:

**Comment by jbzdarkid** [comment]
This fails if the response is a string, so wouldn't that be exactly the case you're talking about?

**Comment by jayme-github** [comment]
No it won't:

``` python
data = {'catpcha_needed': 'True'}
if data.get('catpcha_needed', False): print 'catpcha_needed'
```

I've just pulled your changes in (12abdfb73c9ca2662b2384becbd9264b93369460)

**Comment by jbzdarkid** [comment]
```
data = {'captcha_needed': 'False'}
if data.get('captcha_needed', False): print 'captcha_needed'
```

This code prints captcha_needed.

**Comment by jayme-github** [comment]
Yep, correct and intended. If I remember correctly they send JSON like:

``` json
{"success": "true"}
{"success": ""}
```

Instead of:

``` json
{"success": true}
{"success": false}
```

That's where the code comes from.

**Comment by jbzdarkid** [comment]
Hmm, I was pretty sure they sent False for captcha and email, and they used true/None for success. But if it works, who cares.

**Comment by jayme-github** [comment]
Oh, please don't get me wrong! The do send boolean types now but they did not in the past (at least in some cases). Because of this I continued using the expression that would be True in case of "boolean True" and in case of "any string that is not empty".
Anyways, pulled your changes in for now. I think we're good to go with those.
